project:
  type: website
  output-dir: docs

website:
  title: "Kevin Valdivia"
#  site-url: https://yourwebsite.dev  # Add your site URL if applicable
  description: "Your website description"  # Add a description for the website
  navbar:
    right:
      - href: index.qmd
        text: Home
#      - href: about.qmd
#        text: About
      - text: "Projects"
        menu:
          - href: projects/amlo_mex/amlo_page.qmd
            text: "AMLO Project (under development)"
          - href: projects/the office/office_text_analysis.qmd
            text: "Text Analysis: *The Office*"
      - text: "Tidytuesday"
        menu:
          - href: tidytuesday/school_income.qmd
            text: "Student Income Status at Elite Schools"
          - href: tidytuesday/shakespeare_words.qmd
            text: "Shakespeare Word Cloud"
          - href: tidytuesday/chess_matches.qmd
            text: "Chess Matches"
      - text: "Practice"
        menu:
          - href: practice/ggplot_practice.qmd
            text: "ggplot Practice"
  open-graph:
    locale: en_US
  comments:
    utterances:
      repo: yourusername/yourrepository  # Add your GitHub repo if using Utterances
  page-footer:
    left: "© Copyright 2024 Kevin Valdivia. Except where otherwise noted, all text and images licensed CC-BY-NC 4.0."

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
